# Generated by Django 5.0.6 on 2024-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0004_alter_invention_bd_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_db',
            name='industrial_design_name',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
