# Generated by Django 5.0.6 on 2024-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0005_alter_prom_db_industrial_design_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_db',
            name='patent_grant_publish_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
