# Generated by Django 5.0.6 on 2024-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0007_alter_invention_bd_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invention_bd',
            name='previous_application_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
