# Generated by Django 5.0.6 on 2024-06-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0009_alter_orgs_egrul_status_alter_orgs_id_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='INN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='KPP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='OGRN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='OKFS_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='OKOPF_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='creation_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
