# Generated by Django 5.0.6 on 2024-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0010_alter_orgs_inn_alter_orgs_kpp_alter_orgs_ogrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='creation_time',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
