# Generated by Django 5.0.6 on 2024-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0014_alter_orgs_yr_address_alter_orgs_mail_spark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='EGRUL_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
