# Generated by Django 5.0.6 on 2024-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0015_alter_orgs_egrul_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='OKFS',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
