# Generated by Django 5.0.6 on 2024-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0018_alter_orgs_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='OKVAD2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='OKVAD2_full',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
