# Generated by Django 5.0.6 on 2024-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0019_alter_orgs_okvad2_alter_orgs_okvad2_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
