# Generated by Django 5.0.6 on 2024-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0020_alter_orgs_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='OKVAD2_add',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
    ]
