# Generated by Django 5.0.6 on 2024-06-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0021_alter_orgs_okvad2_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='mail_SPARK',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='tel_SPARK',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
    ]
