# Generated by Django 5.0.6 on 2024-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0023_alter_orgs_okopf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='site',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
