# Generated by Django 5.0.6 on 2024-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0024_alter_orgs_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgs',
            old_name='EGRUL_status',
            new_name='egrul_status',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='ID_child',
            new_name='id_child',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='ID_company',
            new_name='id_company',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='INN',
            new_name='inn',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='KPP',
            new_name='kpp',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OGRN',
            new_name='ogrn',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKFS',
            new_name='okfs',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKFS_code',
            new_name='okfs_code',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKOPF',
            new_name='okopf',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKOPF_code',
            new_name='okopf_code',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKVAD2',
            new_name='okvad2',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKVAD2_add',
            new_name='okvad2_add',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='OKVAD2_full',
            new_name='okvad2_full',
        ),
        migrations.RenameField(
            model_name='orgs',
            old_name='Yr_address',
            new_name='yr_address',
        ),
    ]
