# Generated by Django 5.0.6 on 2024-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0027_alter_orgs_mail_spark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='mail_SPARK',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='tel_SPARK',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
