# Generated by Django 5.0.6 on 2024-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0029_alter_orgs_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prom_bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=13, null=True)),
                ('application_date', models.CharField(blank=True, max_length=10, null=True)),
                ('authors', models.CharField(blank=True, max_length=3000, null=True)),
                ('authors_latin', models.CharField(blank=True, max_length=3000, null=True)),
                ('patent_holders', models.CharField(blank=True, max_length=1500, null=True)),
                ('patent_holders_latin', models.CharField(blank=True, max_length=700, null=True)),
                ('correspondence_address', models.CharField(blank=True, max_length=5500, null=True)),
                ('correspondence_address_latin', models.CharField(blank=True, max_length=1100, null=True)),
                ('industrial_design_name', models.CharField(blank=True, max_length=1200, null=True)),
                ('patent_starting_date', models.CharField(blank=True, max_length=120, null=True)),
                ('crimean_industrial_design_application_number', models.CharField(blank=True, max_length=60, null=True)),
                ('crimean_industrial_design_application_date', models.CharField(blank=True, max_length=70, null=True)),
                ('crimean_industrial_design_patent_number_in_ukraine', models.CharField(blank=True, max_length=10, null=True)),
                ('receipt_date_of_additional_data_to_application', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_application_to_wich_additional_data_has_been_received', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_application_to_wich_additional_data_has_been_received', models.CharField(blank=True, max_length=13, null=True)),
                ('initial_application_number', models.CharField(blank=True, max_length=13, null=True)),
                ('initial_application_date', models.CharField(blank=True, max_length=10, null=True)),
                ('initial_application_priority_date', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_application_number', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_application_date', models.CharField(blank=True, max_length=10, null=True)),
                ('paris_convention_priority_number', models.CharField(blank=True, max_length=1700, null=True)),
                ('paris_convention_priority_date', models.CharField(blank=True, max_length=60, null=True)),
                ('paris_convention_priority_country', models.CharField(blank=True, max_length=350, null=True)),
                ('patent_grant_publish_date', models.CharField(blank=True, max_length=10, null=True)),
                ('patent_grant_publish_number', models.CharField(blank=True, max_length=10, null=True)),
                ('revoke_patent_number', models.CharField(blank=True, max_length=10, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('numbers_of_list_of_essential_features', models.CharField(blank=True, max_length=10, null=True)),
                ('industrial_designs_names_and_number', models.CharField(blank=True, max_length=10, null=True)),
                ('actual', models.CharField(blank=True, max_length=70, null=True)),
                ('publication_url', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_date', models.CharField(blank=True, max_length=100, null=True)),
                ('mkpo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Prom_db',
        ),
    ]
