# Generated by Django 5.0.6 on 2024-06-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0030_prom_bd_delete_prom_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_bd',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
