# Generated by Django 5.0.6 on 2024-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0031_alter_prom_bd_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_bd',
            name='paris_convention_priority_date',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
