# Generated by Django 5.0.6 on 2024-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0034_alter_prom_bd_industrial_design_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_bd',
            name='registration_date',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
