# Generated by Django 5.0.6 on 2024-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0035_alter_prom_bd_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom_bd',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prom_bd',
            name='authors_latin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prom_bd',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prom_bd',
            name='industrial_design_name',
            field=models.CharField(blank=True, max_length=1900, null=True),
        ),
        migrations.AlterField(
            model_name='prom_bd',
            name='paris_convention_priority_number',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
