# Generated by Django 5.0.6 on 2024-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0036_alter_prom_bd_authors_alter_prom_bd_authors_latin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('short_name', models.CharField(blank=True, max_length=500, null=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('yr_address', models.CharField(blank=True, max_length=500, null=True)),
                ('real_address', models.CharField(blank=True, max_length=500, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True)),
                ('head_or_branch', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kpp', models.CharField(blank=True, max_length=50, null=True)),
                ('okopf_code', models.CharField(blank=True, max_length=50, null=True)),
                ('okopf', models.CharField(blank=True, max_length=500, null=True)),
                ('okvad2', models.CharField(blank=True, max_length=500, null=True)),
                ('okvad2_full', models.CharField(blank=True, max_length=2000, null=True)),
                ('creation_time', models.CharField(blank=True, max_length=23, null=True)),
                ('egrul_status', models.CharField(blank=True, max_length=500, null=True)),
                ('okfs_code', models.CharField(blank=True, max_length=50, null=True)),
                ('okfs', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.CharField(blank=True, max_length=10, null=True)),
                ('id_child', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_SPARK', models.CharField(blank=True, max_length=50000, null=True)),
                ('mail_SPARK', models.CharField(blank=True, max_length=50000, null=True)),
                ('site', models.CharField(blank=True, max_length=5000, null=True)),
                ('principal', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=1000, null=True)),
                ('okvad2_add', models.CharField(blank=True, max_length=25000, null=True)),
            ],
        ),
    ]
