# Generated by Django 5.0.6 on 2024-06-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0037_orgs2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgs2',
            name='mail_SPARK',
        ),
    ]
