# Generated by Django 5.0.6 on 2024-06-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0039_orgs_short_delete_orgs_remove_orgs2_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs2',
            name='site',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
