# Generated by Django 5.0.6 on 2024-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0041_orgs3_delete_orgs2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs_short',
            name='creation_time',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='egrul_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='kpp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='okvad2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='okvad2_add',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='okvad2_full',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='principal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='real_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='site',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='tel_SPARK',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='orgs_short',
            name='yr_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
