# Generated by Django 5.0.6 on 2024-06-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0042_orgs_short_creation_time_orgs_short_egrul_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgs_short',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='egrul_status',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='okvad2',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='okvad2_add',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='okvad2_full',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='position',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='real_address',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='site',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='tel_SPARK',
        ),
        migrations.RemoveField(
            model_name='orgs_short',
            name='yr_address',
        ),
    ]
