# Generated by Django 5.0.6 on 2024-06-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0044_orgs_short2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orgs_short',
        ),
    ]
