# Generated by Django 5.0.6 on 2024-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0046_files_delete_orgs3_invention_bd_head_or_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(max_length=500, upload_to='xlsx'),
        ),
    ]
