# Generated by Django 5.0.6 on 2024-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0049_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
