# Generated by Django 5.0.6 on 2024-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0050_reports_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invention_bd',
            name='individual',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmodels_bd',
            name='individual',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prom_bd',
            name='individual',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
