# Generated by Django 5.0.6 on 2024-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_analytics', '0052_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invention_bd',
            name='individual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pmodels_bd',
            name='individual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prom_bd',
            name='individual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
